name: Compile Godot

on: workflow_dispatch
  

jobs:
  compile-windows-editor:
    name: Compile Windows Editor
    runs-on: windows-2022

    steps:
      - name: Checkout Godot repository
        uses: actions/checkout@v4
        with:
          repository: godotengine/godot

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup mingwa
        uses: egor-tensin/setup-mingw@v2
        with: 
          platform: x64

      - name: Setup dependencies
        shell: bash
        run: |
          set -e
          # ANGLE (Windows MinGW binaries)
          mkdir -p deps/angle
          pushd deps/angle
          curl -L -o angle.zip https://github.com/godotengine/godot-angle-static/releases/download/chromium%2F6601.2/godot-angle-static-x86_64-gcc-release.zip
          unzip -o angle.zip && rm angle.zip
          popd

          # Mesa (Windows MinGW binaries)
          mkdir -p deps/mesa
          pushd deps/mesa
          curl -L -o mesa.zip https://github.com/godotengine/godot-nir-static/releases/download/23.1.9-1/godot-nir-static-x86_64-gcc-release.zip
          unzip -o mesa.zip && rm mesa.zip
          popd

          echo "Missing Swappy libraries, downloading them."
          mkdir -p thirdparty/swappy-frame-pacing
          pushd thirdparty/swappy-frame-pacing
          curl -L -O https://github.com/godotengine/godot-swappy/releases/download/from-source-2025-01-31/godot-swappy.7z
          7z x godot-swappy.7z && rm godot-swappy.7z
          popd
        
      - name: Verify dependencies
        shell: bash
        run: |
          echo "ANGLE libraries:"
          ls -l "$PWD"/deps/angle
          echo "Mesa libraries:"
          ls -l "$PWD"/deps/mesa

      - name: Install dependencies
        run: |
          pip3 install scons
          python ./misc/scripts/install_d3d12_sdk_windows.py

          # Add other Windows dependencies here if needed

          
      #- uses: ilammy/msvc-dev-cmd@v1

      - name: "[Windows] Compile Godot..."        
        run: |
          scons verbose=yes warnings=no progress=yes platform=windows arch=x86_64 production=yes use_mingw=yes angle_libs=D:\a\godot-nightly\godot-nightly\deps\angle mesa_libs=D:\a\godot-nightly\godot-nightly\deps\mesa d3d12=yes target=editor

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: godot-windows-${{ github.sha }}
          path: |
            bin/godot.windows.editor.x86_64.exe
            bin/godot.windows.editor.x86_64.console.exe

  compile-windows-templates:
    name: Compile Windows Templates
    runs-on: windows-2022

    steps:
      - name: Checkout Godot repository
        uses: actions/checkout@v4
        with:
          repository: godotengine/godot

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup mingwa
        uses: egor-tensin/setup-mingw@v2
        with: 
          platform: x64
                
      - name: Setup dependencies
        shell: bash
        run: |
          set -e
          # ANGLE (Windows MinGW binaries)
          mkdir -p deps/angle
          pushd deps/angle
          curl -L -o angle.zip https://github.com/godotengine/godot-angle-static/releases/download/chromium%2F6601.2/godot-angle-static-x86_64-gcc-release.zip
          unzip -o angle.zip && rm angle.zip
          popd

          # Mesa (Windows MinGW binaries)
          mkdir -p deps/mesa
          pushd deps/mesa
          curl -L -o mesa.zip https://github.com/godotengine/godot-nir-static/releases/download/23.1.9-1/godot-nir-static-x86_64-gcc-release.zip
          unzip -o mesa.zip && rm mesa.zip
          popd

          echo "Missing Swappy libraries, downloading them."
          mkdir -p thirdparty/swappy-frame-pacing
          pushd thirdparty/swappy-frame-pacing
          curl -L -O https://github.com/godotengine/godot-swappy/releases/download/from-source-2025-01-31/godot-swappy.7z
          7z x godot-swappy.7z && rm godot-swappy.7z
          popd
        
      - name: Verify dependencies
        shell: bash
        run: |
          echo "ANGLE libraries:"
          realpath deps/angle/*
          echo "Mesa libraries:"
          realpath deps/mesa/*

      - name: Install dependencies
        run: |
          pip3 install scons
          python ./misc/scripts/install_d3d12_sdk_windows.py

          # Add other Windows dependencies here if needed
          
      #- uses: ilammy/msvc-dev-cmd@v1

      - name: Build Windows Templates
        run: |
          scons verbose=yes warnings=no progress=no platform=windows arch=x86_64 production=yes mingw=no angle_libs=D:\a\godot-nightly\godot-nightly\deps\angle mesa_libs=D:\a\godot-nightly\godot-nightly\deps\mesa d3d12=yes target=template_debug
          scons verbose=yes warnings=no progress=no platform=windows arch=x86_64 production=yes mingw=no angle_libs=D:\a\godot-nightly\godot-nightly\deps\angle mesa_libs=D:\a\godot-nightly\godot-nightly\deps\mesa d3d12=yes target=template_release
          scons verbose=yes warnings=no progress=no platform=windows arch=x86_32 production=yes mingw=no angle_libs=D:\a\godot-nightly\godot-nightly\deps\angle mesa_libs=D:\a\godot-nightly\godot-nightly\deps\mesa d3d12=yes target=template_debug
          scons verbose=yes warnings=no progress=no platform=windows arch=x86_32 production=yes mingw=no angle_libs=D:\a\godot-nightly\godot-nightly\deps\angle mesa_libs=D:\a\godot-nightly\godot-nightly\deps\mesa d3d12=yes target=template_release

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: godot-windows-templates-${{ github.sha }}
          path: |
            bin/

  compile-android:
    name: Compile Android Editor & Templates
    runs-on: macos-latest

    steps:
      - name: Checkout Godot repository
        uses: actions/checkout@v4
        with:
          repository: godotengine/godot

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup dependencies
        shell: bash
        run: |
          set -e
          if [ ! -d "swappy" ]; then
            echo "Missing Swappy libraries, downloading them."
            mkdir -p thirdparty/swappy-frame-pacing
            pushd thirdparty/swappy-frame-pacing
            curl -L -O https://github.com/godotengine/godot-swappy/releases/download/from-source-2025-01-31/godot-swappy.7z
            7z x godot-swappy.7z && rm godot-swappy.7z
            popd
          fi


      - name: Setup Android SDK/NDK
        uses: android-actions/setup-android@v2
        with:
          ndk-version: 23.2.8568313
          cmdline-tools-version: 9.0

      - name: Install Android dependencies
        run: |
          yes | sdkmanager --licenses
          sdkmanager \
            "build-tools;34.0.0" \
            "platform-tools" \
            "platforms;android-34" \
            "cmake;3.22.1" \
            "ndk;23.2.8568313"

      - name: Install dependencies
        run: |
          pip install scons
          # Add other Windows dependencies here if needed
      
      
      - name: Build Android Templates
        env:
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
          ANDROID_NDK_ROOT: ${{ env.ANDROID_NDK_HOME }}
        run: |

          scons verbose=yes warnings=no progress=no platform=android arch=arm32 production=yes target=template_debug
          scons verbose=yes warnings=no progress=no platform=android arch=arm64 production=yes target=template_debug
          scons verbose=yes warnings=no progress=no platform=android arch=x86_32 production=yes target=template_debug 
          scons verbose=yes warnings=no progress=no platform=android arch=x86_64 production=yes target=template_debug generate_apk=yes

          scons verbose=yes warnings=no progress=no platform=android arch=arm32 production=yes target=template_release
          scons verbose=yes warnings=no progress=no platform=android arch=arm64 production=yes target=template_release
          scons verbose=yes warnings=no progress=no platform=android arch=x86_32 production=yes target=template_release
          scons verbose=yes warnings=no progress=no platform=android arch=x86_64 production=yes target=template_release generate_apk=yes

      #- name: Generate Android Editor/APKs
      #  run: |
      #    cd platform/android/java
      #    ./gradlew generateGodotTemplates

      - name: Upload Android Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: godot-android-templates
          path: |
            bin/android_release.apk
            bin/android_debug.apk
            bin/godot-lib.template_release.aar
            bin/android_source.zip
